//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvertisementId { get; set; }
        public System.DateTime AdStartDate { get; set; }
        public System.DateTime AdEndDate { get; set; }
        public int AdPosition { get; set; }
        public int AdStatus { get; set; }
        public string AdName { get; set; }
        public string AdPhone { get; set; }
        public string AdEmail { get; set; }
        public string AdAddress { get; set; }
        public string AdLink { get; set; }
        public string AdImage { get; set; }
    }
}
