//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidatePostResumes = new HashSet<CandidatePostResume>();
            this.SaveCandidates = new HashSet<SaveCandidate>();
            this.SaveJobs = new HashSet<SaveJob>();
        }
    
        public int CandidateId { get; set; }
        public string Cdd_AspNetUserId { get; set; }
        public Nullable<int> CP_ProfessionId { get; set; }
        public Nullable<int> CP_LevelId { get; set; }
        public Nullable<int> CP_ExperienceId { get; set; }
        public Nullable<int> CP_SalaryId { get; set; }
        public Nullable<int> CP_WorkTypeId { get; set; }
        public string CddUserName { get; set; }
        public string CddPassword { get; set; }
        public string CddFullName { get; set; }
        public string CPAvatar { get; set; }
        public Nullable<int> CddSex { get; set; }
        public string CddAbout { get; set; }
        public string CddAddress { get; set; }
        public string CPPosition { get; set; }
        public string CPExperience { get; set; }
        public string CPSpeciality { get; set; }
        public Nullable<System.DateTime> CPPostDate { get; set; }
        public Nullable<int> CPStatus { get; set; }
        public Nullable<int> Cdd_CityId { get; set; }
        public string CddPhone { get; set; }
        public string CddEmail { get; set; }
        public Nullable<int> CddAge { get; set; }
        public Nullable<System.DateTime> CddRegisterDate { get; set; }
        public string CddFacebook { get; set; }
        public string CddGoogle { get; set; }
        public Nullable<int> Cdd_DistrictId { get; set; }
        public Nullable<int> Cdd_WardId { get; set; }
        public string CddPathCV { get; set; }
        public string CddDescribeCV { get; set; }
        public Nullable<System.DateTime> CddBirthday { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual LevelInfo LevelInfo { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual WorkType WorkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePostResume> CandidatePostResumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveCandidate> SaveCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveJob> SaveJobs { get; set; }
    }
}
