//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int NewsId { get; set; }
        public string NTitle { get; set; }
        public string NQuote { get; set; }
        public string NDetail { get; set; }
        public Nullable<System.DateTime> NPostDate { get; set; }
        public Nullable<System.DateTime> NPublicDate { get; set; }
        public Nullable<int> NType { get; set; }
        public Nullable<int> N_WebmasterInfoId { get; set; }
        public Nullable<int> N_CategoryId { get; set; }
        public Nullable<int> Nstatus { get; set; }
        public string NAvatar { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual WebmasterInfo WebmasterInfo { get; set; }
    }
}
