//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recruit()
        {
            this.RecruitJobs = new HashSet<RecruitJob>();
            this.SaveCandidates = new HashSet<SaveCandidate>();
        }
    
        public int RecruitId { get; set; }
        public string RI_AspNetUserId { get; set; }
        public string RIUserName { get; set; }
        public string RIPassword { get; set; }
        public string RIFullName { get; set; }
        public string RIEmail { get; set; }
        public string RICompanyName { get; set; }
        public string RIAbout { get; set; }
        public string RILogo { get; set; }
        public string RIAddress { get; set; }
        public string RIPhone { get; set; }
        public Nullable<System.DateTime> RIRegisterDate { get; set; }
        public Nullable<int> RIStatus { get; set; }
        public string RIWebsite { get; set; }
        public Nullable<int> RI_CityId { get; set; }
        public Nullable<int> RI_DistrictId { get; set; }
        public Nullable<int> RI_WardId { get; set; }
        public Nullable<System.DateTime> FoundedYear { get; set; }
        public Nullable<int> RI_CompanySizeId { get; set; }
        public Nullable<int> RI_ProfessionId { get; set; }
        public string RICoverImage { get; set; }
        public string RIAvatar { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
        public virtual CompanySize CompanySize { get; set; }
        public virtual District District { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Ward Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruitJob> RecruitJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveCandidate> SaveCandidates { get; set; }
    }
}
