//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecruitJob()
        {
            this.CandidatePostResumes = new HashSet<CandidatePostResume>();
            this.SaveJobs = new HashSet<SaveJob>();
        }
    
        public int RecruitJobId { get; set; }
        public string RJTitle { get; set; }
        public string RJPosition { get; set; }
        public string RJAddress { get; set; }
        public Nullable<int> RJAmount { get; set; }
        public string RJ_Describe { get; set; }
        public string RJ_Require { get; set; }
        public string RJBenefit { get; set; }
        public string RJ_WorkPlace { get; set; }
        public Nullable<System.DateTime> RJPostDate { get; set; }
        public Nullable<System.DateTime> RJExpirationDate { get; set; }
        public string RJEmailContact { get; set; }
        public string RJNameContact { get; set; }
        public string RJPhoneContact { get; set; }
        public Nullable<int> RJGender { get; set; }
        public Nullable<int> RJStatus { get; set; }
        public Nullable<int> RJType { get; set; }
        public Nullable<int> RJ_SalaryId { get; set; }
        public Nullable<int> RJ_ExperienceId { get; set; }
        public Nullable<int> RJ_RecruitId { get; set; }
        public Nullable<int> RJCityId { get; set; }
        public Nullable<int> RJDistrictId { get; set; }
        public Nullable<int> RJ_WardId { get; set; }
        public Nullable<int> RJ_ProfessionId { get; set; }
        public Nullable<int> RJ_LevelId { get; set; }
        public Nullable<int> RJ_WorkTypeId { get; set; }
        public Nullable<int> RJCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePostResume> CandidatePostResumes { get; set; }
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual Experience Experience { get; set; }
        public virtual LevelInfo LevelInfo { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Recruit Recruit { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual WorkType WorkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaveJob> SaveJobs { get; set; }
    }
}
