//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebmasterInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebmasterInfo()
        {
            this.News = new HashSet<New>();
        }
    
        public int WebmasterInfoId { get; set; }
        public string WI_AspNetUserId { get; set; }
        public string WIUserName { get; set; }
        public string WIPassword { get; set; }
        public string WIFullName { get; set; }
        public Nullable<int> WIType { get; set; }
        public Nullable<int> WIStatus { get; set; }
        public Nullable<int> WIGender { get; set; }
        public Nullable<System.DateTime> WIBirthDay { get; set; }
        public Nullable<System.DateTime> WIDateStart { get; set; }
        public string WIAddress { get; set; }
        public Nullable<int> WIPosition { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<New> News { get; set; }
    }
}
