//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunt.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public int WebsiteId { get; set; }
        public string WBanner { get; set; }
        public string WFacebook { get; set; }
        public string WYoutube { get; set; }
        public string WEmail { get; set; }
        public string WPhone { get; set; }
        public string WBanner2 { get; set; }
        public string WBanner3 { get; set; }
    }
}
